<!-- <template>
    <div class="card p-3">
        <h2>Education</h2>
        <ul>
            <li><strong>Elementary:</strong> San Fernando Elementary School</li>
            <li><strong>JHS/SHS:</strong> Information and Communication Technology High School</li>
            <li><strong>College:</strong> Holy Angel University - BSIT</li>
        </ul>
    </div>
</template>

<script>
export default {
    name: "Education"
}
</script> -->