<!-- <template>
    <div class="card p-3">
    <h2>Profile</h2>
        <p><strong>Name:</strong> Aira Mae T. Rosal</p>
        <p><strong>Address:</strong> Fortuna, Floridablanca, Pampanga</p>
        <p><strong>Course:</strong> Bachelor of Science in Information Technology</p>
        <p><strong>Specialization:</strong> Web Development</p>
        <p><strong>Objective:</strong> To apply my skills in programming and continuously grow as a web developer.</p>
    </div>
</template>

<script>
export default {
    name: "Profile"
    data() {
        return {
            msg: 'Profile'
        }
    }
}
</script> -->