<template>
<div class="card p-4 skills-card">
<h2>Skills</h2>
<li><strong>Training:</strong> Web Development Bootcamp</li>
<li><strong>Seminars:</strong> IT Trends Conference</li>
<li><strong>Technologies:</strong> HTML, CSS, JavaScript, Vue</li>
<li><strong>Programming Languages:</strong> Java, Python, PHP</li>
</div>
</template>

 <script>
export default {
name: "Skills"
}
</script>
